## DATA CHECK TASK 4.10

### -Re-checking data and re-checking some results due to main large notebook crashing and new notebook will save time and prevent computer problems

In [1]:
# Importing libraries to computer
import pandas as pd
import numpy as np
import os

In [2]:
# Creating a data importing shortcut called 'path' for the Instacart folder to make importing data easier and cleaner
path =r'/Users/drewsmith/Desktop/01-2023 Instacart Basket Analysis'

In [3]:
# Utilizing the created 'path' shortcut to import the 'Products' dataset 
df_prods = pd.read_csv(os.path.join(path, '02 Data', 'Original Data', 'products.csv'), index_col = False)

In [4]:
df_prods.shape

(49693, 5)

In [5]:
# Utilizing the created 'path' shortcut to import the 'Products' dataset 
prods_check = pd.read_csv(os.path.join(path, '02 Data', 'Prepared Data', 'products_checked.csv'), index_col = False)

In [6]:
prods_check.shape

(49672, 6)

In [7]:
# Utilizing the created 'path' shortcut to import the 'new_ords_prods_merge' dataset 
ords_prods = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'cus_ords_prods.pkl'))

In [8]:
ords_prods.shape

(32404859, 34)

In [9]:
# Utilizing the created 'path' shortcut to import the 'new_ords_prods_merge' dataset 
ords_merg = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'orders_products_merged.pkl'))

In [10]:
ords_merg.shape

(32404859, 15)

In [11]:
# Utilizing the created 'path' shortcut to import the 'new_ords_prods_merge' dataset 
ords_upd = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'updated_orders_products_merged.pkl'))

In [12]:
ords_upd.shape

(32404859, 19)

In [13]:
# Utilizing the created 'path' shortcut to import the 'new_ords_prods_merge' dataset 
ords_new = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'new_ords_prods_merge.pkl'))

In [14]:
ords_new.shape

(32404859, 25)

In [15]:
# Utilizing the created 'path' shortcut to import the 'new_ords_prods_merge' dataset 
final1 = pd.read_pickle(os.path.join(path, '02 Data', 'Prepared Data', 'final_insta_data.pkl'))

In [32]:
final1.head(50)

,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order,loyalty_flag,spending_flag,avg_user_price,median_days_prior_order,order_frequency_flag,gender,state,age,date_joined,num_of_dependants,marriage_status,income,region,exclusion_flag,age_flag,income_flag,pet_owner_flag
0,2539329,1,1,2,8,NaN,196,1,0,Soda,77,7,9.0,Mid-range product,Regularly busy,Regular days,Average orders,10,New customer,Low spender,6.367797,20.5,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,High-activity,Adult,Lower-middle class,Family w/out pet
1,2398795,1,2,3,7,15.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,Average orders,10,New customer,Low spender,6.367797,20.5,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,High-activity,Adult,Lower-middle class,Family w/out pet
2,473747,1,3,3,12,21.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Slowest days,Most orders,10,New customer,Low spender,6.367797,20.5,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,High-activity,Adult,Lower-middle class,Family w/out pet
3,2254736,1,4,4,7,29.0,196,1,1,Soda,77,7,9.0,Mid-range product,Least busy,Slowest days,Average orders,10,New customer,Low spender,6.367797,20.5,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,High-activity,Adult,Lower-middle class,Family w/out pet
4,431534,1,5,4,15,28.0,196,1,1,Soda,77,7,9.0,Mid-range product,Least busy,Slowest days,Most orders,10,New customer,Low spender,6.367797,20.5,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,High-activity,Adult,Lower-middle class,Family w/out pet
5,3367565,1,6,2,7,19.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Regular days,Average orders,10,New customer,Low spender,6.367797,20.5,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,High-activity,Adult,Lower-middle class,Family w/out pet
6,550135,1,7,1,9,20.0,196,1,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,Low spender,6.367797,20.5,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,High-activity,Adult,Lower-middle class,Family w/out pet
7,3108588,1,8,1,14,14.0,196,2,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,Low spender,6.367797,20.5,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,High-activity,Adult,Lower-middle class,Family w/out pet
8,2295261,1,9,1,16,0.0,196,4,1,Soda,77,7,9.0,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,Low spender,6.367797,20.5,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,High-activity,Adult,Lower-middle class,Family w/out pet
9,2550362,1,10,4,8,30.0,196,1,1,Soda,77,7,9.0,Mid-range product,Least busy,Slowest days,Average orders,10,New customer,Low spender,6.367797,20.5,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,High-activity,Adult,Lower-middle class,Family w/out pet
10,2539329,1,1,2,8,NaN,14084,2,0,Organic Unsweetened Vanilla Almond Milk,91,16,12.5,Mid-range product,Regularly busy,Regular days,Average orders,10,New customer,Low spender,6.367797,20.5,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,High-activity,Adult,Lower-middle class,Family w/out pet
11,2539329,1,1,2,8,NaN,12427,3,0,Original Beef Jerky,23,19,4.4,Low-range product,Regularly busy,Regular days,Average orders,10,New customer,Low spender,6.367797,20.5,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,High-activity,Adult,Lower-middle class,Family w/out pet
12,2398795,1,2,3,7,15.0,12427,3,1,Original Beef Jerky,23,19,4.4,Low-range product,Regularly busy,Slowest days,Average orders,10,New customer,Low spender,6.367797,20.5,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,High-activity,Adult,Lower-middle class,Family w/out pet
13,473747,1,3,3,12,21.0,12427,2,1,Original Beef Jerky,23,19,4.4,Low-range product,Regularly busy,Slowest days,Most orders,10,New customer,Low spender,6.367797,20.5,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,High-activity,Adult,Lower-middle class,Family w/out pet
14,2254736,1,4,4,7,29.0,12427,2,1,Original Beef Jerky,23,19,4.4,Low-range product,Least busy,Slowest days,Average orders,10,New customer,Low spender,6.367797,20.5,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,High-activity,Adult,Lower-middle class,Family w/out pet
15,431534,1,5,4,15,28.0,12427,2,1,Original Beef Jerky,23,19,4.4,Low-range product,Least busy,Slowest days,Most orders,10,New customer,Low spender,6.367797,20.5,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,High-activity,Adult,Lower-middle class,Family w/out pet
16,3367565,1,6,2,7,19.0,12427,2,1,Original Beef Jerky,23,19,4.4,Low-range product,Regularly busy,Regular days,Average orders,10,New customer,Low spender,6.367797,20.5,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,High-activity,Adult,Lower-middle class,Family w/out pet
17,550135,1,7,1,9,20.0,12427,3,1,Original Beef Jerky,23,19,4.4,Low-range product,Regularly busy,Busiest days,Most orders,10,New customer,Low spender,6.367797,20.5,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,High-activity,Adult,Lower-middle class,Family w/out pet
18,3108588,1,8,1,14,14.0,12427,1,1,Original Beef Jerky,23,19,4.4,Low-range product,Regularly busy,Busiest days,Most orders,10,New customer,Low spender,6.367797,20.5,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,High-activity,Adult,Lower-middle class,Family w/out pet
19,2295261,1,9,1,16,0.0,12427,6,1,Original Beef Jerky,23,19,4.4,Low-range product,Regularly busy,Busiest days,Most orders,10,New customer,Low spender,6.367797,20.5,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,High-activity,Adult,Lower-middle class,Family w/out pet
20,2550362,1,10,4,8,30.0,12427,9,1,Original Beef Jerky,23,19,4.4,Low-range product,Least busy,Slowest days,Average orders,10,New customer,Low spender,6.367797,20.5,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,High-activity,Adult,Lower-middle class,Family w/out pet
21,2539329,1,1,2,8,NaN,26088,4,0,Aged White Cheddar Popcorn,23,19,4.7,Low-range product,Regularly busy,Regular days,Average orders,10,New customer,Low spender,6.367797,20.5,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,High-activity,Adult,Lower-middle class,Family w/out pet
22,2398795,1,2,3,7,15.0,26088,5,1,Aged White Cheddar Popcorn,23,19,4.7,Low-range product,Regularly busy,Slowest days,Average orders,10,New customer,Low spender,6.367797,20.5,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,High-activity,Adult,Lower-middle class,Family w/out pet
23,2539329,1,1,2,8,NaN,26405,5,0,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,Low-range product,Regularly busy,Regular days,Average orders,10,New customer,Low spender,6.367797,20.5,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,High-activity,Adult,Lower-middle class,Family w/out pet
24,2254736,1,4,4,7,29.0,26405,5,1,XL Pick-A-Size Paper Towel Rolls,54,17,1.0,Low-range product,Least busy,Slowest days,Average orders,10,New customer,Low spender,6.367797,20.5,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,High-activity,Adult,Lower-middle class,Family w/out pet
25,2398795,1,2,3,7,15.0,10258,2,0,Pistachios,117,19,3.0,Low-range product,Regularly busy,Slowest days,Average orders,10,New customer,Low spender,6.367797,20.5,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,High-activity,Adult,Lower-middle class,Family w/out pet
26,473747,1,3,3,12,21.0,10258,3,1,Pistachios,117,19,3.0,Low-range product,Regularly busy,Slowest days,Most orders,10,New customer,Low spender,6.367797,20.5,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,High-activity,Adult,Lower-middle class,Family w/out pet
27,2254736,1,4,4,7,29.0,10258,3,1,Pistachios,117,19,3.0,Low-range product,Least busy,Slowest days,Average orders,10,New customer,Low spender,6.367797,20.5,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,High-activity,Adult,Lower-middle class,Family w/out pet
28,431534,1,5,4,15,28.0,10258,3,1,Pistachios,117,19,3.0,Low-range product,Least busy,Slowest days,Most orders,10,New customer,Low spender,6.367797,20.5,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,High-activity,Adult,Lower-middle class,Family w/out pet
29,3367565,1,6,2,7,19.0,10258,3,1,Pistachios,117,19,3.0,Low-range product,Regularly busy,Regular days,Average orders,10,New customer,Low spender,6.367797,20.5,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,High-activity,Adult,Lower-middle class,Family w/out pet
30,550135,1,7,1,9,20.0,10258,2,1,Pistachios,117,19,3.0,Low-range product,Regularly busy,Busiest days,Most orders,10,New customer,Low spender,6.367797,20.5,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,High-activity,Adult,Lower-middle class,Family w/out pet
31,3108588,1,8,1,14,14.0,10258,3,1,Pistachios,117,19,3.0,Low-range product,Regularly busy,Busiest days,Most orders,10,New customer,Low spender,6.367797,20.5,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,High-activity,Adult,Lower-middle class,Family w/out pet
32,2295261,1,9,1,16,0.0,10258,5,1,Pistachios,117,19,3.0,Low-range product,Regularly busy,Busiest days,Most orders,10,New customer,Low spender,6.367797,20.5,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,High-activity,Adult,Lower-middle class,Family w/out pet
33,2550362,1,10,4,8,30.0,10258,6,1,Pistachios,117,19,3.0,Low-range product,Least busy,Slowest days,Average orders,10,New customer,Low spender,6.367797,20.5,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,High-activity,Adult,Lower-middle class,Family w/out pet
34,2398795,1,2,3,7,15.0,13176,4,0,Bag of Organic Bananas,24,4,10.3,Mid-range product,Regularly busy,Slowest days,Average orders,10,New customer,Low spender,6.367797,20.5,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,High-activity,Adult,Lower-middle class,Family w/out pet
35,431534,1,5,4,15,28.0,13176,8,1,Bag of Organic Bananas,24,4,10.3,Mid-range product,Least busy,Slowest days,Most orders,10,New customer,Low spender,6.367797,20.5,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,High-activity,Adult,Lower-middle class,Family w/out pet
36,2398795,1,2,3,7,15.0,13032,6,0,Cinnamon Toast Crunch,121,14,4.0,Low-range product,Regularly busy,Slowest days,Average orders,10,New customer,Low spender,6.367797,20.5,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,High-activity,Adult,Lower-middle class,Family w/out pet
37,550135,1,7,1,9,20.0,13032,5,1,Cinnamon Toast Crunch,121,14,4.0,Low-range product,Regularly busy,Busiest days,Most orders,10,New customer,Low spender,6.367797,20.5,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,High-activity,Adult,Lower-middle class,Family w/out pet
38,2550362,1,10,4,8,30.0,13032,8,1,Cinnamon Toast Crunch,121,14,4.0,Low-range product,Least busy,Slowest days,Average orders,10,New customer,Low spender,6.367797,20.5,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,High-activity,Adult,Lower-middle class,Family w/out pet
39,473747,1,3,3,12,21.0,25133,4,0,Organic String Cheese,21,16,8.6,Mid-range product,Regularly busy,Slowest days,Most orders,10,New customer,Low spender,6.367797,20.5,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,High-activity,Adult,Lower-middle class,Family w/out pet
40,2254736,1,4,4,7,29.0,25133,4,1,Organic String Cheese,21,16,8.6,Mid-range product,Least busy,Slowest days,Average orders,10,New customer,Low spender,6.367797,20.5,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,High-activity,Adult,Lower-middle class,Family w/out pet
41,431534,1,5,4,15,28.0,25133,4,1,Organic String Cheese,21,16,8.6,Mid-range product,Least busy,Slowest days,Most orders,10,New customer,Low spender,6.367797,20.5,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,High-activity,Adult,Lower-middle class,Family w/out pet
42,3367565,1,6,2,7,19.0,25133,4,1,Organic String Cheese,21,16,8.6,Mid-range product,Regularly busy,Regular days,Average orders,10,New customer,Low spender,6.367797,20.5,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,High-activity,Adult,Lower-middle class,Family w/out pet
43,550135,1,7,1,9,20.0,25133,4,1,Organic String Cheese,21,16,8.6,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,Low spender,6.367797,20.5,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,High-activity,Adult,Lower-middle class,Family w/out pet
44,3108588,1,8,1,14,14.0,25133,4,1,Organic String Cheese,21,16,8.6,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,Low spender,6.367797,20.5,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,High-activity,Adult,Lower-middle class,Family w/out pet
45,2295261,1,9,1,16,0.0,25133,3,1,Organic String Cheese,21,16,8.6,Mid-range product,Regularly busy,Busiest days,Most orders,10,New customer,Low spender,6.367797,20.5,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,High-activity,Adult,Lower-middle class,Family w/out pet
46,2550362,1,10,4,8,30.0,25133,5,1,Organic String Cheese,21,16,8.6,Mid-range product,Least busy,Slowest days,Average orders,10,New customer,Low spender,6.367797,20.5,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,High-activity,Adult,Lower-middle class,Family w/out pet
47,473747,1,3,3,12,21.0,30450,5,0,Creamy Almond Butter,88,13,3.2,Low-range product,Regularly busy,Slowest days,Most orders,10,New customer,Low spender,6.367797,20.5,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,High-activity,Adult,Lower-middle class,Family w/out pet
48,431534,1,5,4,15,28.0,10326,5,0,Organic Fuji Apples,24,4,2.7,Low-range product,Least busy,Slowest days,Most orders,10,New customer,Low spender,6.367797,20.5,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,High-activity,Adult,Lower-middle class,Family w/out pet
49,431534,1,5,4,15,28.0,17122,6,0,Honeycrisp Apples,24,4,14.0,Mid-range product,Least busy,Slowest days,Most orders,10,New customer,Low spender,6.367797,20.5,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,High-activity,Adult,Lower-middle class,Family w/out pet

In [30]:
# Doesn't assign any options to the max number of columns so the 'head()' function can display all columns
pd.options.display.max_columns = None

In [16]:
final1.shape

(32404859, 35)

In [17]:
# Utilizing the created 'path' shortcut to import the 'Products' dataset 
cus = pd.read_csv(os.path.join(path, '02 Data', 'Original Data', 'customers.csv'), index_col = False)

In [18]:
cus.shape

(206209, 10)

In [19]:
# Displays only rows that are duplicates in df_ords1 dataframe under a new subset
cus_dups = cus[cus.duplicated()]

In [20]:
cus_dups

Empty DataFrame
Columns: [user_id, First Name, Surnam, Gender, STATE, Age, date_joined, n_dependants, fam_status, income]
Index: []

In [24]:
# Used to find missing observations or entries in the products dataframe
cus.isnull().sum()

user_id             0
First Name      11259
Surnam              0
Gender              0
STATE               0
Age                 0
date_joined         0
n_dependants        0
fam_status          0
income              0
dtype: int64

In [23]:
# Utilizing the created 'path' shortcut to import the 'new_ords_prods_merge' dataset 
dff = pd.read_csv(os.path.join(path, '02 Data', 'Original Data', 'order_products__prior.csv'), index_col = False)

In [25]:
# Displays only rows that are duplicates in df_ords1 dataframe under a new subset
ords_dups = dff[dff.duplicated()]

In [27]:
ords_dups

Empty DataFrame
Columns: [order_id, product_id, add_to_cart_order, reordered]
Index: []

In [26]:
# Used to find missing observations or entries in the products dataframe
dff.isnull().sum()

order_id             0
product_id           0
add_to_cart_order    0
reordered            0
dtype: int64

In [28]:
dff.shape

(32434489, 4)